export default [
  {
    id: 't1',
    title: 'Lead Hand Punch',
    belt: 'Tan',
    description:
      'The lead hand punch is a snapping straight punch executed by the forward or lead hand. It is a fast, unexpected punch designed to stun an aggressor and to set up for a follow-on techniques. A lead hand punch conceals movement and allows you to get close to the aggressor.',
    execution: [
      'Assume the basic warrior stance.',
      'Snap your lead hand out to nearly full extension, while rotating your palm to the deck.',
      'Keep your rear hand in place to protect your head.',
      'Rapidly retract to the basic warrior stance.',
    ],
    proTip:
      'A common mistake is to pull the fist back low, leaving you open to a counter attack. Ensure you do not hyperextend your elbows',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://youtu.be/8Oxwfhd_L0Q?feature=shared',
    },
    mastered: false,
  },
  {
    id: 't2',
    title: 'Rear Hand Punch',
    belt: 'Tan',
    description:
      'The rear hand punch is a snapping punch executed by the rear hand. It is a power punch designed to inflict maximum damage on your aggressor. Its power comes from pushing off your rear leg and rotating your hips and shoulders.',
    execution: [
      'Assume the basic warrior stance.',
      'Forcefully rotate your hips and shoulders toward the aggressor and thrust your rear hand straight out, palm down, to nearly full extension.',
      'Shift your body weight to your lead foot while pushing off on the ball of your rear foot.',
      'Keep your lead hand in place to protect your head.',
      'Rapidly retract to the basic warrior stance.',
    ],
    proTip:
      'A common mistake is to pull the fist back low, leaving you open to a counter attack. Ensure you do not hyperextend your elbows',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://youtu.be/ofil5E5lPCY?feature=shared',
    },
    mastered: false,
  },
  {
    id: 't3',
    title: 'Uppercut',
    belt: 'Tan',
    description:
      "The uppercut is a powerful punch originating below the aggressor's line of vision. It is executed in an upward motion traveling up the centerline of the aggressor's body. It is delivered in close and usually follows a preparatory strike that leaves the target area unprotected. When delivered to the chin or jaw, the uppercut can render an aggressor unconscious, cause extensive damage to the neck, and/or sever the tongue.",
    execution: [
      ' Assume the basic warrior stance.',
      ' Rotate your fist so your palm is facing you. Ensure your lead hand stays up and in place to protect your head.',
      ' Power is generated from low to high. Start with your body weight low and legs slightly bent. Explode upwards with your legs, hips, and shoulders, driving your fist straight up through the target area.',
      ' Rapidly retract to the basic warrior stance.',
    ],
    proTip:
      'A common mistake is to drop the fist to the waist in an attempt to generate more power. Power is generated from the correct use of the lower body.',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/5LXsw2VfrOg?si=YFUX3n1gZehr2fvi',
    },
    mastered: false,
  },
  {
    id: 't4',
    title: 'Hook',
    belt: 'Tan',
    description:
      'The hook is a powerful punch that is executed close-in and is usually preceded by a preparatory strike.',
    execution: [
      ' Assume the basic warrior stance.',
      ' Rotate your rear fist, this will parallel your fist and forearm to the deck.',
      ' Power is generated from side to side by driving with your legs and rotating your hips and shoulders. Your body’srotation drives the fist through your target area as your lead hand stays up and in place to protect your head.',
      ' Rapidly retract to the basic warrior stance.',
    ],
    proTip:
      'A common mistake is to reach or extend the fist all the way out in an attempt to generate more power. Power is generated from the rotation of the hips and shoulders.',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/_nCUoFrqibk?si=CLu3yeW1XYfNr4w9',
    },
    mastered: false,
  },
  {
    id: 't5',
    title: 'Eye Gouge',
    belt: 'Tan',
    description:
      'The eye gouge is used to attack the aggressor’s eyes, blinding him so follow on techniques can be executed.',
    execution: [
      'From the basic warrior stance, open your left hand with your fingers spread apart and slightly bent.',
      "With the palm of your hand either toward the ground or toward the sky, thrust your left hand forward into the aggressor's eyes.",
      "Thrust your hand at the aggressor's nose level so your fingers can slide naturally into the grooves of their eye sockets.",
      'Return to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/AZvW31qC4vc?si=mcnYpG_JZWXsyAjj',
    },
    mastered: false,
  },
  {
    id: 't6',
    title: 'Horizontal Hammer Fist',
    belt: 'Tan',
    description:
      'Striking with the hammer fist concentrates power in a small part of the hand which can have a devastating effect when transferred to the target.',
    execution: [
      'From the basic warrior stance, retract your right hand so your fist is next to your face. Simultaneously rotate your right hip and shoulder backwards.',
      'Thrust your fist forward onto the aggressor while rotating your right hip and shoulder forward. Rotate your wrist so the meaty portion of your fist makes contact on the aggressor.',
      'Follow through the target area with your fist.',
      'Return to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/o8eqizg-IFw?si=7O_gj8u3VaTvM6Mz',
    },
    mastered: false,
  },
  {
    id: 't7',
    title: 'Vertical Hammer Fist',
    belt: 'Tan',
    description:
      'Striking with the hammer fist concentrates power in a small part of the hand which, when transferred to the target, can have a devastating effect.',
    execution: [
      'From the basic warrior stance, retract your right hand so your fist is next to your face. Simultaneously rotate your right hip and shoulder backwards.',
      'Thrust your fist straight down onto the aggressor while dropping your body weight. Rotate your wrist so the meaty portion of your fist makes contact on the aggressor.',
      'Follow through the target area with your fist.',
      'Return to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/iEfiIQC1NQA?si=svXoE3sLbqjm3mI9',
    },
    mastered: false,
  },
  {
    id: 't8',
    title: 'Vertical Elbow Strike, Low to High',
    belt: 'Tan',
    description:
      'Elbow strikes are close range weapons that inflict a great amount of damage due to leverage and the transfer of your body weight.',
    execution: [
      'From the basic warrior stance, bend your right elbow keeping your fist close to your body. Your fist is at shoulder level and your elbow is next to your torso.',
      'Thrust your elbow vertically upward toward the aggressor. Keep your elbow bent throughout the movement.',
      'Rotate your right shoulder and hip forward and drive up with your legs to generate power.',
      'Make contact on the aggressor with your right forearm two inches above the point of the elbow.',
      'Return to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/74pmwIZcn10?si=rSEZrLW1SvRZekJV',
    },
    mastered: false,
  },
  {
    id: 't9',
    title: 'Forward Horizontal Elbow Strike',
    belt: 'Tan',
    description:
      'Elbow strikes are close range weapons that inflict a great amount of damage due to leverage and the transfer of your body weight.',
    execution: [
      'From the basic warrior stance, bring your elbow up and tuck your right fist near your chest with the palm facing the deck.',
      'Thrust your right elbow horizontally forward toward the aggressor, keeping your forearm parallel to the deck.',
      'Keep your fist tucked near your chest with the palm heel facing the ground, and keep your elbow bent throughout the movement.',
      'Rotate your right shoulder and hip forward to generate power.',
      'Return to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/xHrDVdlzV08?si=cnxzU9b5YkHGZqi9',
    },
    mastered: false,
  },
  {
    id: 't10',
    title: 'Rear Choke',
    belt: 'Tan',
    description:
      'The rear choke is performed when you are behind the aggressor, when he is on the ground, or when you are taking him to the ground.',
    execution: [
      'Begin with the aggressor kneeling on the deck while you stand behind him.',
      'With your right arm, reach over the aggressor’s right shoulder and hook the bend of your arm around his neck. Your chest should be against the aggressor’s back.',
      'Clasp both hands together, palm-on-palm, with your right palm facing the deck.',
      'Ensure the aggressor’s trachea is positioned within the bend of your arm, but pressure is not being exerted on it.',
      'Exert pressure with your right biceps and radius bone on the aggressor’s carotid arteries, on both sides of the neck.',
      'Maintain pressure on both sides of the neck and draw the aggressor closer to you by pulling your right arm in.',
      "To increase the effectiveness of the choke, apply forward pressure to the back of the aggressor's head with your head.",
    ],
    proTip:
      "If the aggressor is taller than you, step or push on the back of the aggressor's knee with your foot. This will off-balance the aggressor, causing him to bend at the knees and fall forward.",
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/LQqpWmQ01SI?si=nwW-DcVAubUvKucw',
    },
    mastered: false,
  },
  {
    id: 't11',
    title: 'Figure 4 Variation',
    belt: 'Tan',
    description:
      'The figure-four is a variation that allows you to gain more leverage on the rear choke. If you cannot secure the rear choke, you may apply the figure-four variation to increase the pressure of the choke on the aggressor.',
    execution: [
      "Apply a rear choke. Your body should be against the aggressor's body.",
      "Bring your left arm over the aggressors left shoulder, grasp your left biceps or shoulder with your right hand, and place your left hand against the back of the aggressor's head.",
      "Push the aggressor's head forward and down with your left hand, keeping your elbows in.",
      "Draw your right arm in, maintaining pressure with your biceps and forearm on both sides of the aggressor's neck.",
    ],
    proTip:
      "If the aggressor is taller than you, step or push on the back of the aggressor's knee with your foot. This will off-balance the aggressor, causing him to bend at the knees and fall forward.",
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/dpHo0zG93mY?si=4GmmJ2zaLUBeEt3s',
    },
    mastered: false,
  },
  {
    id: 't12',
    title: 'Leg Sweep',
    belt: 'Tan',
    description:
      'A leg sweep is particularly effective if the aggressor is moving backward or pulling on you.',
    execution: [
      'tart facing the aggressor in the basic warrior stance.',
      "Step forward with your left foot on the outside of the aggressor's right foot. Your foot should be on line or behind the aggressor's foot, and far enough outside to provide room to bring the other leg through to execute the sweep.",
      "At the same time, grab the aggressor’s right wrist with your left hand and his left shoulder with your right hand. You may grab the aggressor's flesh, clothing, or gear.",
      'Off-balance the aggressor by pulling his wrist downward close to your trouser pocket and pushing his shoulder backward.',
      "Raise your right knee waist high and bring your foot behind the aggressor's right leg. The leg should be bent at the knee because it takes less movement than straightening the leg prior to the sweep. When your leg is raised you should be balanced while the aggressor is off-balance.",
      "Sweep through the aggressor’s leg, making contact with your calf on the aggressor's calf. At the same time, continue to pull the aggressor’s right wrist and push his left shoulder.",
      "Drive the aggressor to the deck by bending at the waist, and following through his leg with the sweep. Release your grip on the aggressor's shoulder in order to maintain your balance.",
      'Rapidly return to the basic warrior stance.',
    ],
    proTip:
      'Ensure calf on calf contact is being made. In a combative engagement contact will be made with the cutting edge of your heel on the aggressor’s Achilles tendon.',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/6dBm98BHzo8?si=ev5rtn8l97CVs6sJ',
    },
    mastered: false,
  },
  {
    id: 't13',
    title: 'Front Kick',
    belt: 'Tan',
    description:
      'The front kick is used to stop the aggressor’s forward momentum or to set him up for follow on techniques when the aggressor is in front of you.',
    execution: [
      'From the basic warrior stance, raise your right knee waist high and pivot your hips into the attack, thrusting your right foot forward toward the aggressor. You may have to shift your body weight to your left leg to maintain balance.',
      'Never extend your foot above waist high, and keep in mind it is difficult to change the direction of a kick after it is initiated.',
      'Make contact on the aggressor with the toe of your right boot or bootlaces.',
      'Follow through the target with your foot and rapidly retract to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/K_JpSishBiI?si=Q95JYAvmgiW1mwSE',
    },
    mastered: false,
  },
  {
    id: 't14',
    title: 'Round Kick',
    belt: 'Tan',
    description:
      'The round kick is used to cause maximum damage to the knee or to set up the aggressor for follow on techniques.',
    execution: [
      'From the basic warrior stance, point the foot of your left leg 45 degrees to the outside of the aggressor and raise your right leg slightly off the deck. You may have to shift your body weight to your left leg to maintain balance.',
      'With your left leg slightly bent, thrust your right leg forward in an arcing motion towards the aggressor, rotating your hips and shoulders into the attack.',
      'Make contact on the aggressor with the shin of the right leg or the top of the foot.',
      'Follow through the target with your foot and rapidly retract to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/K_JpSishBiI?si=Q95JYAvmgiW1mwSE',
    },
    mastered: false,
  },
  {
    id: 't15',
    title: 'Vertical Stomp',
    belt: 'Tan',
    description:
      'The vertical stomp is used to attack the aggressor when he is on the deck and you are standing.',
    execution: [
      'From the basic warrior stance, raise the knee of your right foot above waist level. Your right leg should be bent at a 90 degree angle. Shift your body weight to your left leg to maintain your balance.',
      'Forcefully drive the flat bottom of your right boot down onto the aggressor while keeping your right knee slightly bent.',
      'At the same time, bend your left knee slightly to drop your body weight into the strike.',
      'Rapidly retract to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/K_JpSishBiI?si=Q95JYAvmgiW1mwSE',
    },
    mastered: false,
  },
  {
    id: 't16',
    title: 'Vertical Knee Strike',
    belt: 'Tan',
    description:
      'The vertical knee strike is used to inflict major damage during close range fighting or grappling.',
    execution: [
      'From the basic warrior stance, grab the aggressor’s neck or gear with both hands without interlacing your fingers. If you interlace your fingers, your aggressor can pull back or reach behind their head and break the fingers.',
      'Pull the aggressor down and at the same time raise your right knee driving it up forcefully into the aggressor. Power is generated by pulling the aggressor down and thrusting the leg upward with your hips.',
      'Follow through the target with your knee and rapidly retract to the basic warrior stance.',
    ],
    proTip: '',
    defaultTip: 'Ensure proper safety and warm-up to avoid injuries.',
    video: {
      title: 'YouTube video player',
      width: 560,
      height: 315,
      url: 'https://www.youtube.com/embed/ZaRTJZwXorI?si=4cpuIpwKyyG5tqbq',
    },
    mastered: false,
  },
];
